### ISSUE TITLE
Cached device count

### ISSUE THREAD

**Issue by bayleedev** [codepope/BigRedButtonNodeHID#5]
When I call `deviceCount()` it returns 0, I plug in a device and it still returns 0.

**Comment by bayleedev** [comment]
It looks like this is intentional. Was there a reason for this?

https://github.com/codepope/BigRedButtonNodeHID/blob/master/BigRedButton.js#L16-L19

**Comment by codepope** [comment]
It’s a singleton to ensure the HID.devices() call is called once and it’s value is cached.

**Comment by codepope** [comment]
To be honest, I didn’t plan on the device being plugged and unplugged during the lifetime of the app.

**Comment by bayleedev** [comment]
Would you rather have a `reset()` method? or something similar?

**Comment by codepope** [comment]
Just checked in a bit of a rework - now the device update always happens. I've added a "buttonGone" event to handle the button being removed and I've modified the test to focus on one button and to wait till a button is plugged in, or wait when its removed. There may be a race condition still at the nodehid layer, but if this is the behaviour we want, then, thats a debugging issue.
